inherit_from: .rubocop_todo.yml

require:
  - rubocop/cop/internal_affairs

AllCops:
  TargetRubyVersion: 2.5

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/rubocop-graphql.rb

Naming/PredicateName:
  Enabled: false
