require:
  - rubocop/cop/internal_affairs
  - rubocop-graphql

AllCops:
  TargetRubyVersion: 2.5

GraphQL/ObjectDescription:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/rubocop-graphql.rb

Naming/PredicateName:
  Enabled: false

GraphQL/MaxComplexitySchema:
  Exclude:
    - lib/rubocop/cop/graphql/max_complexity_schema.rb
    - lib/rubocop/cop/graphql/max_depth_schema.rb

GraphQL/MaxDepthSchema:
  Exclude:
    - lib/rubocop/cop/graphql/max_complexity_schema.rb
    - lib/rubocop/cop/graphql/max_depth_schema.rb

# FIXME: Workaround for a false positive caused by this cop when using `bundle exec rake`.
InternalAffairs/UndefinedConfig:
  Enabled: false
